import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import type { WordCandidate, WordEntry } from '../../src/data/words/wordTypes.ts';

type CategoryRule = {
  category: string;
  keywords: string[];
};

const categoryRules: CategoryRule[] = [
  {
    category: 'どうぶつ',
    keywords: [
      'ねこ',
      'いぬ',
      'うし',
      'うま',
      'ぶた',
      'とり',
      'さる',
      'くま',
      'しか',
      'きつね',
      'たぬき',
      'うさぎ',
      'ぞう',
      'きりん',
      'らいおん',
      'とら',
      'へび',
      'かめ',
      'かえる',
      'いか',
      'たこ',
      'えび',
      'かに',
      'さかな',
      'くじら',
      'いるか',
      'ねずみ',
      'りす',
      'ぱんだ',
      'こあら',
      'あひる',
      'からす',
      'すずめ',
      'はと',
      'わし',
      'むし',
      'ちょう',
      'あり',
      'はち',
    ],
  },
  {
    category: 'たべもの',
    keywords: [
      'ぱん',
      'ごはん',
      'めし',
      'こめ',
      'もち',
      'めん',
      'そば',
      'うどん',
      'らーめん',
      'すし',
      'にく',
      'やさい',
      'くだもの',
      'りんご',
      'いちご',
      'ばなな',
      'みかん',
      'ぶどう',
      'もも',
      'なし',
      'かき',
      'くり',
      'まめ',
      'いも',
      'たまご',
      'ぎゅうにゅう',
      'ちゃ',
      'じゅーす',
      'さけ',
      'みそ',
      'しお',
      'さとう',
      'しょうゆ',
      'かれー',
      'すーぷ',
      'さらだ',
      'けーき',
      'ちょこ',
      'あめ',
      'がむ',
      'くっきー',
      'ぱすた',
    ],
  },
  {
    category: 'のりもの',
    keywords: [
      'くるま',
      'ばす',
      'でんしゃ',
      'れっしゃ',
      'ちかてつ',
      'しんかんせん',
      'ひこうき',
      'ふね',
      'じてんしゃ',
      'ばいく',
      'たくしー',
      'とらっく',
      'へり',
      'ろけっと',
      'よっと',
    ],
  },
  {
    category: 'どうぐ',
    keywords: [
      'はさみ',
      'えんぴつ',
      'ぺん',
      'けしごむ',
      'のーと',
      'じょうぎ',
      'かさ',
      'つくえ',
      'いす',
      'かばん',
      'ほん',
      'はこ',
      'びん',
      'さら',
      'こっぷ',
      'なべ',
      'ふらいぱん',
      'すぷーん',
      'ふぉーく',
      'ないふ',
      'かぎ',
      'とけい',
      'でんわ',
      'かめら',
      'ぱそこん',
      'てれび',
      'らじお',
      'ぼたん',
      'ねじ',
      'はんまー',
      'のこぎり',
    ],
  },
  {
    category: 'きもち',
    keywords: [
      'うれし',
      'たのし',
      'かなし',
      'さみし',
      'こわ',
      'おこ',
      'いかり',
      'あんしん',
      'ふあん',
      'すき',
      'きらい',
      'ありがとう',
      'ごめん',
      'えがお',
      'なみだ',
      'びっくり',
    ],
  },
  {
    category: 'しぜん',
    keywords: [
      'やま',
      'かわ',
      'うみ',
      'そら',
      'もり',
      'はやし',
      'はな',
      'くさ',
      'いし',
      'つち',
      'すな',
      'あめ',
      'ゆき',
      'かぜ',
      'くも',
      'ほし',
      'つき',
      'たいよう',
      'みず',
      'いけ',
      'たに',
      'しま',
      'なみ',
      'はる',
      'なつ',
      'あき',
      'ふゆ',
    ],
  },
  {
    category: 'からだ',
    keywords: [
      'あたま',
      'かお',
      'みみ',
      'はな',
      'くち',
      'あし',
      'ゆび',
      'からだ',
      'こころ',
      'はら',
      'せなか',
      'こし',
      'ひざ',
      'くび',
      'かた',
      'うで',
    ],
  },
  {
    category: 'がっこう',
    keywords: [
      'がっこう',
      'せんせい',
      'せいと',
      'きょうしつ',
      'こくご',
      'さんすう',
      'りか',
      'しゃかい',
      'おんがく',
      'たいいく',
      'しゅくだい',
      'じゅぎょう',
      'てすと',
      'こくばん',
    ],
  },
  {
    category: 'いえ',
    keywords: [
      'いえ',
      'へや',
      'だいどころ',
      'ふろ',
      'といれ',
      'げんかん',
      'まど',
      'かべ',
      'やね',
      'にわ',
      'べっど',
      'ふとん',
      'たな',
    ],
  },
  {
    category: 'まち',
    keywords: [
      'まち',
      'えき',
      'みせ',
      'こうえん',
      'どうろ',
      'はし',
      'びる',
      'びょういん',
      'ぎんこう',
      'ゆうびん',
      'こうばん',
      'としょかん',
      'れすとらん',
      'ほてる',
    ],
  },
];

function classify(word: string): string {
  for (const rule of categoryRules) {
    if (rule.keywords.some((keyword) => word.includes(keyword))) {
      return rule.category;
    }
  }
  return 'ふつう';
}

function sourceName(candidate: WordCandidate): string {
  return `SudachiDict ${candidate.source.dictionary}`;
}

const root = resolve(process.cwd());
const candidatesPath = resolve(root, 'src/data/words/wordCandidates.json');
const wordsPath = resolve(root, 'src/data/words/words.quest.json');
const candidates = JSON.parse(readFileSync(candidatesPath, 'utf8')) as WordCandidate[];

const words: WordEntry[] = candidates.map((candidate, index) => {
  const category = classify(candidate.word);
  return {
    id: `word-${String(index + 1).padStart(5, '0')}`,
    word: candidate.word,
    reading: candidate.reading,
    normalized: candidate.normalized,
    mainCategory: category,
    categories: [category],
    facts: [],
    kana: candidate.kana,
    source: {
      type: 'sudachi',
      name: sourceName(candidate),
      dictionary: candidate.source.dictionary,
      candidateId: candidate.id,
      autoFlags: candidate.autoFlags,
    },
    reviewStatus: 'approved',
  };
});

writeFileSync(wordsPath, `${JSON.stringify(words, null, 2)}\n`, 'utf8');

const counts = words.reduce<Record<string, number>>((acc, word) => {
  acc[word.mainCategory] = (acc[word.mainCategory] ?? 0) + 1;
  return acc;
}, {});

console.log(JSON.stringify({ total: words.length, counts }, null, 2));
